### ISSUE TITLE
Incorrect attribute key for source tag in files/zone.xml line 11

### ISSUE THREAD

**Issue by RemiWoler** [tinuva/firewalld-formula#1]
In https://github.com/tinuva/firewalld-formula/blob/master/firewalld/files/zone.xml#L11 , the value v is assigned to attribute key 'name'. This is incorrect, the attribute key is called 'address'. 

Source: man firewalld.zone(5). 

My own testing also confirmed that with attribute key 'name' the zone is not picked up with a source value, but it is picked up for attribute key 'address'.

**Comment by tinuva** [comment]
Thank you for making this issue, I completely missed it. Fixed it in the following commit: https://github.com/tinuva/firewalld-formula/commit/b584c44edcd61c5e94ceb90572cda44d4c7a7a1f
