### ISSUE TITLE
All files in files/ have unknown Jinja variable 'header' 

### ISSUE THREAD

**Issue by RemiWoler** [tinuva/firewalld-formula#2]
Jinja error: Unable to manage file: Jinja variable 'dict object' has no attribute 'headers'; line 1

This requires the same fix as done in: https://dl.heaven.za.net/salt-formulas/firewalld-formula/commit/bad41c90280f4b7839f8aa17750c67a1afcbfab5

~RW

P.S. Thanks for sharing your formula, even with the ""issues"" it saved me a ton of time creating my own.

**Comment by tinuva** [comment]
Issue fixed by pull https://github.com/tinuva/firewalld-formula/pull/3
