### ISSUE TITLE
could this formula be added https://github.com/saltstack-formulas

### ISSUE THREAD

**Issue by aboe76** [tinuva/firewalld-formula#5]
saltstack has a github repo to share formulas

Read this part on sharing:
http://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#writing-formulas

Maybe you would like this formula to be added to that repo? you can keep this repo as upstream.

**Comment by aboe76** [comment]
Do I have permission to submit firewalld-formula to saltstack formulas? so others can contribute as well?

**Comment by tinuva** [comment]
my apologies for only replying now. I did read through the above link the first time last year, and was a bit too busy to comply with all of the guidelines set out.

Did a quick clean up of most commented out lines that is not needed.

Answering your question: I give you permission to upload the firewalld-formula to saltstack formulas on github.

**Comment by aboe76** [comment]
@tinuva the information you removed could that be added to the Readme,
because it is usefull to know.

Do you want me to ask saltstack-formula's to fork it and leave you're github as upstream,
so you can merge contributions back?

**Comment by tinuva** [comment]
If possible for them to do that, that will be awesome, otherwise I dont mind at all having this project donated to them, as I can see how it will help others going forward.

**Comment by aboe76** [comment]
OK I have forked the repo in the saltstack-formula's repo,
